/**
 * 测试用配置 fixture
 * 提供完整的 Config 对象，避免每个测试重复构造
 */
import type { Config } from '@/config/schema';

export function createTestConfig(overrides?: Partial<Config>): Config {
  return {
    app: {
      name: 'test',
      version: '0.0.0-test',
      log_level: 'warn',
      max_shops: 5,
      data_dir: './test-data',
      single_instance: false,
    },
    vision: {
      enabled: false,
      python_path: 'python',
      script_path: 'vision.py',
      start_timeout_ms: 1000,
      request_timeout_ms: 1000,
      poll_interval_ms: 500,
      max_restart_per_hour: 3,
    },
    ocr: {
      lang: 'ch',
      use_angle_cls: false,
      use_gpu: false,
      max_text_length: 200,
      text_clean_rules: [],
    },
    cdp: {
      port_range: [9222, 9230],
      startup_args: ['--remote-debugging-port={port}'],
      startup_delay_ms: 100,
      max_retries: 2,
      retry_interval_ms: 100,
      heartbeat: { interval_ms: 1000, timeout_ms: 2000, failures_threshold: 2 },
      recover_probe: {
        interval_ms: 1000,
        cooldown_after_failure_ms: 1000,
        verify_count: 2,
        verify_interval_ms: 100,
        verify_timeout_ms: 2000,
      },
      client_keepalive: {
        interval_ms: 1000,
        restart_max_per_hour: 3,
        stuck_detection: { cpu_threshold_percent: 5, duration_ms: 60000 },
      },
    },
    deepseek: {
      api_url: 'https://api.deepseek.com/v1/chat/completions',
      model: 'deepseek-v4-flash',
      temperature: 0.2,
      max_tokens: 800,
      top_p: 0.9,
      timeout_ms: 8000,
      stream: false,
      retry_count: 1,
      retry_interval_ms: 100,
      context_rounds: 5,
      context_idle_clear_ms: 300000,
      fallback_response: 'fallback',
      prompt_template: 'template',
      sensitive_words_dict: '',
      balance: {
        warn_threshold_yuan: 10,
        critical_threshold_yuan: 2,
        check_interval_ms: 3600000,
      },
    },
    ratelimit: {
      per_shop_per_minute: 5,
      night_factor: 0.7,
      night_hours: [0, 7],
      burst_allowance: 2,
      burst_window_ms: 10000,
    },
    cache: {
      ttl_ms: 3600000,
      max_entries_per_shop: 100,
      max_entries_global: 1000,
      invalidate_on_product_update: true,
    },
    human_simulator: {
      reply_delay: {
        default: { min_ms: 100, max_ms: 200 },
      },
      typing_speed_min_cpm: 120,
      typing_speed_max_cpm: 220,
      segment_pause: { min_chars: 3, max_chars: 8, min_ms: 10, max_ms: 30 },
      cursor_jitter: true,
      typing_mistake_rate: 0,
    },
    silent_wait: { duration_ms: 60000, max_consecutive: 3 },
    product: {
      cache_index_in_memory: true,
      match_algorithm: 'hybrid',
      fuzzy_threshold: 0.7,
      keywords_weight: 0.4,
      fuzzy_match_weight: 0.6,
      fallback_to_human: true,
      auto_sync: { enabled: false, cron: '0 3 * * *', api_url: '' },
    },
    logging: {
      level: 'warn',
      retention_days: 7,
      rotation_max_bytes: 10485760,
      audit_retention_days: 180,
      sanitize: {
        phone: true,
        id_card: true,
        email: true,
        bank_card: true,
        address: true,
        address_dict: '',
      },
    },
    monitor: {
      metrics_flush_interval_ms: 10000,
      metrics_retention_days: 7,
      alert: {
        feishu_webhook: '',
        feishu_secret: '',
        sms_access_key: '',
        sms_access_secret: '',
        sms_phone_numbers: [],
        dedup_window_ms: 300000,
        maintenance_windows: [],
      },
    },
    security: {
      api_key_store: 'dpapi',
      api_key_env_var: 'DEEPSEEK_API_KEY',
      audit_all_replies: true,
      reply_output_check: true,
      max_consecutive_sensitive: 1,
    },
    platforms: {
      feige: { web_url: '' },
      pinduoduo: { web_url: '' },
      kuaishou: { web_url: '' },
      weixin: { web_url: '' },
    },
    agents: {
      enabled: true,
      list: [
        { id: 'after_sales', scenario: 'after_sales', keywords: ['退货', '退款', '换货'], preferred_tier: 'tier3', priority: 90 },
        { id: 'logistics', scenario: 'logistics', keywords: ['物流', '快递', '发货'], preferred_tier: 'tier2', priority: 70 },
        { id: 'product_expert', scenario: 'product_comparison', keywords: ['对比', '推荐', '尺码'], preferred_tier: 'tier3', priority: 80 },
        { id: 'general', scenario: 'general', keywords: [], preferred_tier: 'tier2', priority: 50 },
      ],
    },
    gateway: {
      enabled: true,
      cascade: {
        enabled: true,
        confidence_thresholds: { tier1: 0.75, tier2: 0.70, tier3: 0.60 },
        max_depth: 3,
      },
      providers: {
        deepseek: { enabled: true, tier: 'tier3' },
        qwen: {
          enabled: false,
          tier: 'tier2',
          api_url: 'https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions',
          api_key_env_var: 'QWEN_API_KEY',
          model: 'qwen-plus',
          timeout_ms: 8000,
        },
        local: {
          enabled: false,
          tier: 'tier1',
          api_url: 'http://localhost:11434/api/chat',
          model: 'qwen2.5:7b',
          timeout_ms: 5000,
        },
      },
    },
    scheduler: {
      enabled: true,
      token_bucket: { daily_budget_yuan: 50, reserve_ratio: 0.2 },
      budget: {
        global_daily_yuan: 100,
        global_monthly_yuan: 2000,
        per_shop_daily_yuan: 5,
        warn_threshold: 0.8,
        critical_threshold: 1.0,
      },
      default_priority: 'normal',
    },
    learning: {
      enabled: true,
      run_interval_ms: 21600000,
      lookback_hours: 24,
      min_quality_threshold: 0.75,
      min_samples_for_pattern: 3,
      semantic_threshold: 0.8,
      pattern_decay_days: 30,
      max_patterns_per_shop: 500,
      weights: {
        confidence: 0.30,
        latency: 0.15,
        structure: 0.15,
        safety: 0.20,
        feedback: 0.20,
      },
    },
    intent: {
      enabled: true,
      complexity_threshold: 0.6,
      confidence_threshold: 0.5,
      history_weight: 0.3,
    },
    conversion: {
      enabled: true,
      max_recommendations: 3,
      cross_sell_threshold: 0.4,
      recommendation_cooldown_ms: 300000,
    },
    human_collab: {
      enabled: true,
      queue_poll_interval_ms: 10000,
      max_wait_ms: 300000,
      default_max_chats: 5,
      auto_transfer_on_escalation: true,
    },
    ...overrides,
  };
}
