import React from 'react';

const createIcon = (name: string) => {
  const Icon = ({ size, ...props }: { size?: number; [key: string]: unknown }) =>
    React.createElement('span', { 'data-testid': `icon-${name}`, ...props });
  Icon.displayName = name;
  return Icon;
};

export const Settings = createIcon('Settings');
export const Home = createIcon('Home');
export const Package = createIcon('Package');
export const ListChecks = createIcon('ListChecks');
export const BookOpen = createIcon('BookOpen');
export const ScrollText = createIcon('ScrollText');
export const MessagesSquare = createIcon('MessagesSquare');
export const FileText = createIcon('FileText');
export const Brain = createIcon('Brain');
export const TrendingUp = createIcon('TrendingUp');
export const Activity = createIcon('Activity');
export const Users = createIcon('Users');
export const BarChart3 = createIcon('BarChart3');
export const Sparkles = createIcon('Sparkles');
export const Info = createIcon('Info');
export const Database = createIcon('Database');
export const Search = createIcon('Search');
export const Zap = createIcon('Zap');
export const ThumbsUp = createIcon('ThumbsUp');
export const ThumbsDown = createIcon('ThumbsDown');
export const MessageSquare = createIcon('MessageSquare');
export const Shield = createIcon('Shield');
export const AlertTriangle = createIcon('AlertTriangle');
export const Clock = createIcon('Clock');
export const Plus = createIcon('Plus');
export const Trash2 = createIcon('Trash2');
export const Download = createIcon('Download');
export const Upload = createIcon('Upload');
export const Edit2 = createIcon('Edit2');
export const Star = createIcon('Star');
export const RefreshCw = createIcon('RefreshCw');
export const UserCheck = createIcon('UserCheck');
export const Bird = createIcon('Bird');
export const Moon = createIcon('Moon');
export const Sun = createIcon('Sun');
export const Heart = createIcon('Heart');
export const Inbox = createIcon('Inbox');
export const CheckCircle = createIcon('CheckCircle');
export const XCircle = createIcon('XCircle');
export const Reply = createIcon('Reply');
export const ArrowDownToLine = createIcon('ArrowDownToLine');
export const ChevronDown = createIcon('ChevronDown');
export const ChevronRight = createIcon('ChevronRight');
export const ChevronLeft = createIcon('ChevronLeft');
export const Send = createIcon('Send');
export const Bell = createIcon('Bell');
export const MoreHorizontal = createIcon('MoreHorizontal');
export const ClipboardList = createIcon('ClipboardList');
export const Image = createIcon('Image');
export const Smile = createIcon('Smile');
export const Type = createIcon('Type');
export const Check = createIcon('Check');
export const Minus = createIcon('Minus');
export const FlaskConical = createIcon('FlaskConical');
export const ShieldCheck = createIcon('ShieldCheck');
export const Copy = createIcon('Copy');
export const AlertCircle = createIcon('AlertCircle');
export const Loader2 = createIcon('Loader2');
export const X = createIcon('X');
export const MoreVertical = createIcon('MoreVertical');
export const Store = createIcon('Store');
export const UserRound = createIcon('UserRound');
export const Stethoscope = createIcon('Stethoscope');
export const CheckCircle2 = createIcon('CheckCircle2');
export const SkipForward = createIcon('SkipForward');
export const Gauge = createIcon('Gauge');
export const Cpu = createIcon('Cpu');
export const Paperclip = createIcon('Paperclip');
export const User = createIcon('User');
export const PackageSearch = createIcon('PackageSearch');
export const Hand = createIcon('Hand');
export const ShoppingBag = createIcon('ShoppingBag');
export const Settings2 = createIcon('Settings2');
